apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/robclusterdev/DevSecOpsReact.git  # Update with your actual repository
    targetRevision: main
    path: kubernetes
    directory:
      recurse: true
      exclude: "argocd/*,monitoring/*"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 