apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# This is a minimal ArgoCD installation manifest
# For production, consider a full installation following the official documentation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: argocd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # Default password is 'admin' - change this in production
  admin.password: "$2a$10$5m.XgRcMrVl7MSrg4KLVi.yZdTIrfoaRGQFEZpJhcXjFMiL3dMPl2"
  admin.passwordMtime: "2023-01-01T00:00:00Z"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd:v2.9.3
        args:
        - argocd-server
        - --insecure
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30 