apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecopsreact
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MichaelRobotics/DevSecOpsReact.git  # Update this with your actual repository URL
    targetRevision: main
    path: kubernetes
    directory:
      exclude: "{argocd/**,monitoring/**}"  # Exclude argocd and monitoring directories
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true