apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: react-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: react-app
  endpoints:
    - port: http
      path: /metrics