name: S3 Backend Deployment

on:
#  push:
#    branches: [ main ]
#    paths:
#      - 'EKS/backend/**'
#      - '.github/workflows/s3-backend-deployment.yml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

jobs:
  terraform-backend:
    name: Deploy S3 Terraform Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./EKS/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        if: github.event.inputs.action != 'destroy'
      
      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan
        if: github.event.inputs.action == 'destroy'

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        
      - name: Display Backend Information
        if: github.event.inputs.action != 'destroy'
        run: |
          BUCKET=$(terraform output -raw s3_bucket)
          TABLE=$(terraform output -raw dynamodb_table)
          
          echo "S3 bucket: $BUCKET"
          echo "DynamoDB table: $TABLE"
          echo ""
          echo "IMPORTANT: These values must match the ones configured in EKS/main.tf backend block:"
          echo "Expected bucket: devsecopsreact-dev-terraform-state"
          echo "Expected table: devsecopsreact-dev-terraform-locks"
          
          if [ "$BUCKET" != "devsecopsreact-dev-terraform-state" ]; then
            echo "WARNING: S3 bucket name mismatch! Update EKS/main.tf or recreate the backend."
          fi
          
          if [ "$TABLE" != "devsecopsreact-dev-terraform-locks" ]; then
            echo "WARNING: DynamoDB table name mismatch! Update EKS/main.tf or recreate the backend."
          fi 